### ISSUE TITLE
Register.php

### ISSUE THREAD

**Issue by gosse02** [Line-Lan/ALP-LineLan#1]
After changing line 252 in the install.php from TYPE to ENGINE I was able to get the database populated but on the next step register.php I get a timeout page took too long to respond. Any ideas?

This site can’t be reached

"website name" took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

**Comment by L1n3m4st3r** [comment]
Setting up a test environment at the moment. I will try to reproduce this issue. You will hear back when finished.

**Comment by L1n3m4st3r** [comment]
Tested with php5 and php7. Could not reproduce this issue. Install works without any issues in my testing environment (Debian8 with apache2.4, php7.0.9/5.6.24, mysql5.5.50). Usually when there is a problem with the code, php throws an HTTP error 500. A timeout like in your issue means, that either the database is unreachable or your webserver is hanging somewere. It's unlikely that it is related to php itself.

But thanks for pointing out the issue with TYPE to ENIGINE, as TYPE is deprecated and was removed in mysql 5.5.

Also note that the codebase was written around 2004/2006 and might have some incompatibilities or a different behaviour on modern systems.

**Comment by gosse02** [comment]
Line-Lan,

 

Still can’t get it to work even with a fresh install. I have installed alp xampp and it works fine but I can’t get past the https register.php page. Any help is appreciated.
